apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 995830900532.dkr.ecr.ap-south-1.amazonaws.com/ci-cd-app
    newTag: 5ba3fc3af432023a28e651d2b3af1d2d8c0f7de3