apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 995830900532.dkr.ecr.ap-south-1.amazonaws.com/ci-cd-app
    newTag: 4767ea563fc5c3c8ef99051da33d06306e79403e